#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys

voron_user = "pi"
voron_address = "voron.local"

local_prefix = os.path.realpath(os.path.dirname(__file__))
voron_home = f"/home/{voron_user}"
files = [
    { "local": f"{local_prefix}/files/printer.cfg", "voron": f"{voron_home}/klipper_config/printer.cfg" },
    { "local": f"{local_prefix}/files/printer/leds.cfg", "voron": f"{voron_home}/klipper_config/printer/leds.cfg" }
]

def command_line_args():
    parser = argparse.ArgumentParser(
        prog = os.path.basename(__file__),
        description = 'Download and upload Voron config for centralized tracking in Git.')

    parser.add_argument(
        'action',
        choices=["upload", "download"],
        help="Download from or upload to the Voron?"
        )

    return parser.parse_args()

def scp(source, target):
    print(f"Copy [{source}] to [{target}]", file=sys.stderr)
    subprocess.run(["scp", "-r", source, target])

def copy_all(mode):
    for file_pair in files:
        match file_pair:
            case {"local": local, "voron": voron}:
                voron_scp = f"{voron_user}@{voron_address}:{voron}"
                if mode == "download":
                    scp(source=voron_scp, target=local)
                elif mode == "upload":
                    scp(source=local, target=voron_scp)
                else:
                    raise ValueError(f"mode can only be upload/downoad, but is {mode}")
            case _:
                raise ValueError(f"Bad file pair structure: {file_pair.keys()}. Check the config block of this script at {os.path.realpath(__file__)}!")

def main():
    args = command_line_args()
    copy_all(args.action)

if __name__ == '__main__':
    try:
        main()
    except ValueError as e:
        print(f"Error: {str(e)}")
